package:
  name: aaaa
  dependencies:
    - console
    - effect
    - prelude
  test:
    main: Test.Main
    dependencies: []
workspace:
  packageSet:
    path: local-package-set.json
  extraPackages: {}
